---

- name: Register backup timestamp
  command: date --iso=seconds
  register: backup_timestamp
  changed_when: false


- name: Have containers running for database backup
  systemd:
    name: mattermost.service
    state: started

- name: Create backup directory
  file:
    path: "{{ mm_docker_backup_path }}/{{ backup_timestamp.stdout }}"
    state: directory
    recurse: true
  register: backup_dir

- name: Backup database
  shell: >
    docker exec -t docker_postgres_1 pg_dump -U {{ mm_postgres_user }}
    {{ mm_postgres_db }} > {{ backup_dir.path }}/db.sql"

- name: Stop containers for volume backup
  systemd:
    name: mattermost.service
    state: stopped

- name: Ensure rsync packages is installed
  apt:
    name: rsync
    state: present

- name: Backup volumes
  command: >
    rsync -a {{ mm_docker_volumes_path }} {{ backup_dir.path }}

- name: Start containers after volume backup
  systemd:
    name: mattermost.service
    state: started
