---

- name: Install packages
  apt:
    name: git
    state: present

- name: Clone mattermost-docker
  git:
    repo: https://github.com/mattermost/docker
    dest: "{{ mm_docker_src_path }}"
    version: "{{ mm_docker_version }}"
    force: "{{ mattermost_docker_upgrade }}"
    update: "{{ mattermost_docker_upgrade }}"

- name: Copy custom configuration
  template:
    src: env.j2
    dest: "{{ mm_docker_src_path }}/.env"
    owner: root
    group: root
    mode: 0640

- name: Check that HTTPs certificates exist
  stat:
    path: "{{mm_cert}}"
  register: cert_exists

- name: Create certs directory
  file:
    path: "{{ mm_certs_path }}"
    state: directory
  when: not cert_exists.stat.exists

- name: Generate certificates for the first time
  shell: >
    docker run -it --rm --name certbot -p 80:80
    -v {{mm_certs_path}}/etc/letsencrypt:/etc/letsencrypt
    -v {{mm_certs_path}}/lib/letsencrypt:/var/lib/letsencrypt
    certbot/certbot certonly --standalone -d {{mm_domain}}
    --non-interactive --agree-tos --email {{lets_encrypt_email}}
  when: not cert_exists.stat.exists
  register: certbot_result
  tags: notest

- name: Print certificate generation output
  debug:
    var: certbot_result.stdout_lines
  when: not cert_exists.stat.exists
  tags: notest

- name: Update volume directory permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mm_docker_uid }}"
    group: "{{ mm_docker_gid }}"
    recurse: true
  with_items:
    - "{{ mm_config_path }}"
    - "{{ mm_data_path }}"
    - "{{ mm_logs_path }}"
    - "{{ mm_plugins_path }}"
    - "{{ mm_client_path  }}"
    - "{{ mm_bleve_indexes_path }}"
    - "{{ mm_nginx_config_path }}"

- name: Template systemd unit
  template:
    src: mattermost.service.j2
    dest: /etc/systemd/system/mattermost.service
    owner: root
    group: root
    mode: 0644
  register: unit

- name: Reload daemons
  systemd:
    daemon_reload: true
  when: unit.changed

- name: Enable service
  systemd:
    name: mattermost.service
    enabled: true

- name: Build images
  docker_compose:
    project_src: "{{ mm_docker_src_path }}"
    files: ["docker-compose.yml", "docker-compose.nginx.yml"]
    state: present
    stopped: true
    build: "{{ mattermost_docker_upgrade }}"

- name: Start containers
  systemd:
    name: mattermost.service
    state: restarted

- name: User information
  debug:
    msg: >
      You can now login to your Mattermost instance and do the initial setup.
      Run the restart-mattermost.yml playbook when you are done.
  when: not mattermost_docker_upgrade
