---

- include_tasks: backup-create.yml
  when: mattermost_docker_upgrade

- name: Remove images and containers before rebuilding for upgrade
  docker_compose:
    project_src: "{{ mm_docker_src_path }}"
    state: absent
  when: mattermost_docker_upgrade

- include_tasks: install.yml
  when: mattermost_docker_upgrade or mattermost_docker_install
