---

#- include_tasks: backup.yml
#  when: mattermost_docker_upgrade

- name: Remove images and containers before rebuilding for upgrade
  docker_compose:
    project_src: "{{ mattermost_docker_src_path }}"
    state: absent
  when: mattermost_docker_upgrade

- include_tasks: install.yml
  when: mattermost_docker_install is defined and mattermost_docker_install

- include_tasks: restart.yml
  when: mattermost_docker_restart is defined and mattermost_docker_restart

