---

driver:
  name: vagrant
  provider:
    name: libvirt

lint: |
  set -e
  yamllint .

platforms:
  - name: debian11-instance
    box: generic/debian11
    memory: 2000
    cpus: 2
    groups:
      - mattermost

provisioner:
  name: ansible
  options:
    verbose: true
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: ./playbooks/deploy.yml

verifier:
  name: testinfra
  directory: tests
  options:
    verbose: true
  lint:
     name: flake8

dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
