---

- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      openssh_keypair:
        path: /tmp/id_ssh_rsa
      register: m_ssh_key
    # Satisfy CI Molecule error
    # Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)
    - name: Install python-package
      apt:
        name: python3-pip

    - name: Installs Docker
      apt:
        pkg: ['python3-docker']
        state: present

    - name: Ensures docker-compose is installed (via pip)
      pip:
        name: docker-compose
        state: present
