---

- name: "Deploy a Mattermost server"
  hosts: "mattermost"
  become: true
  pre_tasks:
    - name: check which containers are running
      command: docker ps

  roles:
    - role: mattermost
      vars:
        mattermost_docker_restart: yes
        mattermost_docker_upgrade: yes
