---

- name: "Deploy a Mattermost server"
  hosts: "mattermost"
  become: true

  roles:
    - role: geerlingguy.docker
    - role: mattermost
      vars:
        mattermost_docker_install: yes
        # previous mattermost version
        mm_version: "6.9"

- import_playbook: ./upgrade.yml
