---

- name: "Deploy a Mattermost server"
  hosts: "mattermost"
  become: true

  tasks:
    - name: Pause for 5 minutes to let containers start fully
      ansible.builtin.pause:
        minutes: 5

  roles:
    - role: mattermost
      vars:
        mattermost_docker_restart: yes
        mattermost_docker_upgrade: yes
