---

- name: "Deploy a Mattermost server"
  hosts: "mattermost"
  become: true

  roles:
    - role: mattermost
      vars:
        mattermost_docker_restart: yes
        mattermost_docker_upgrade: yes
